"""Report builders: JSON and self-contained HTML."""

from __future__ import annotations

import datetime as dt
import html
import json

SEVERITY_ORDER = {"high": 0, "medium": 1, "low": 2, "info": 3}
SEVERITY_COLORS = {"high": "#ff453a", "medium": "#ff9f0a", "low": "#ffd60a", "info": "#0a84ff"}


def build_report(identity: str, findings: list[dict]) -> dict:
    ordered = sorted(findings, key=lambda f: (SEVERITY_ORDER.get(f["severity"], 9), f["service"], f["resource"]))
    counts = {sev: sum(1 for f in findings if f["severity"] == sev) for sev in SEVERITY_COLORS}
    return {
        "tool": "stratus",
        "identity": identity,
        "scanned_at": dt.datetime.now(tz=dt.timezone.utc).isoformat(),
        "summary": counts,
        "findings": ordered,
    }


def to_json(report: dict) -> str:
    return json.dumps(report, indent=2)


def to_html(report: dict) -> str:
    e = html.escape
    counts = " · ".join(
        f'<span class="pill" style="border-color:{SEVERITY_COLORS[s]};color:{SEVERITY_COLORS[s]}">{s.upper()}: {n}</span>'
        for s, n in report["summary"].items()
    )
    cards = "".join(
        f'<article class="finding"><span class="sev" style="background:{SEVERITY_COLORS[f["severity"]]}">'
        f'{f["severity"].upper()}</span><div><h3>{e(f["title"])}</h3>'
        f'<p class="meta"><code>{e(f["service"])}</code> · <code>{e(f["resource"])}</code> · {e(f["check"])}</p>'
        f'<p>{e(f["detail"])}</p></div></article>'
        for f in report["findings"]
    ) or '<p class="none">No findings — clean posture.</p>'
    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>Stratus report</title>
<style>
:root{{color-scheme:dark}}
*{{box-sizing:border-box}}body{{margin:0;background:#0b0d10;color:#e8eaed;
font-family:-apple-system,BlinkMacSystemFont,"SF Pro Text",Inter,Arial,sans-serif;padding:40px 20px}}
.wrap{{max-width:960px;margin:0 auto}}
h1{{font-size:34px;letter-spacing:-.02em;margin:0}}
.sub{{color:#9aa0a6;margin:6px 0 26px}}code{{font-family:ui-monospace,Menlo,monospace;font-size:.92em}}
.summary{{display:flex;gap:10px;flex-wrap:wrap;margin-bottom:30px}}
.pill{{border:1px solid;padding:7px 14px;border-radius:980px;font-size:12px;font-weight:700;letter-spacing:.06em}}
h2{{font-size:20px;margin:34px 0 16px}}
.finding{{display:flex;gap:16px;background:#14171c;border:1px solid #23262b;border-radius:14px;padding:18px;margin-bottom:12px}}
.sev{{flex:none;align-self:flex-start;font-size:11px;font-weight:800;padding:5px 10px;border-radius:7px;color:#000}}
.finding h3{{margin:0 0 6px;font-size:16px}}.finding p{{margin:4px 0;color:#bdc1c6;font-size:14px;line-height:1.55}}
.meta{{color:#9aa0a6!important;font-size:12.5px!important}}
.none{{color:#9aa0a6}}.foot{{margin-top:44px;color:#5f6368;font-size:12px}}
</style></head><body><div class="wrap">
<h1>☁️ Stratus report</h1>
<p class="sub">Identity <code>{e(report["identity"])}</code> · scanned {e(report["scanned_at"])}</p>
<div class="summary">{counts}</div>
<h2>Findings ({len(report["findings"])})</h2>
{cards}
<p class="foot">Generated by <b>stratus</b> — only assess accounts you own or are authorized to audit.</p>
</div></body></html>
"""
